name: ccsds
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - numpy>=1.20
  - numba>=0.57
  - scipy>=1.7
  - matplotlib>=3.5
  - pytest>=6
  - zarr>=2,<3
  - pip
  - pip:
      - -e .
